package org.bb.vityok.novinar;

import java.io.Serializable;

import java.util.Calendar;

import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;

/** Representation of the news item from a news feed. */
public class NewsItem
    implements Serializable
{
    private SimpleIntegerProperty id = new SimpleIntegerProperty();
    private SimpleStringProperty title = new SimpleStringProperty();
    private SimpleStringProperty link = new SimpleStringProperty();
    private SimpleStringProperty description = new SimpleStringProperty();
    private SimpleStringProperty creator = new SimpleStringProperty();
    private SimpleStringProperty date = new SimpleStringProperty();
    private SimpleStringProperty subject = new SimpleStringProperty();
    private Calendar cDate;

    public NewsItem () {
        cDate = new Calendar.Builder().setInstant(System.currentTimeMillis()).build();
    }

    /** Every news item has a unique ID automatically generated by a
     * database sequence.
     */
    public int getNewsItemId() { return id.get(); }
    public void setNewsItemId(int id) { this.id.set(id); }

    public String getTitle() { return title.get(); }
    public void setTitle(String title) { this.title.set(title); }

    public String getLink() { return link.get(); }
    public void setLink(String link) { this.link.set(link); }

    public String getDescription() { return description.get(); }
    public void setDescription(String description) { this.description.set(description); }

    public String getCreator() { return creator.get(); }
    public void setCreator(String creator) { this.creator.set(creator); }

    public String getDate() { return date.get(); }
    public void setDate(String date) { this.date.set(date); }

    public Calendar getDateCalendar() {
	return cDate;
    }

    public void setDateCalendar(Calendar cDate) {
        this.cDate = cDate;
    }

    public String getSubject() { return subject.get(); }
    public void setSubject(String subject) { this.subject.set(subject); }
}
